#元组
#不可便与可变序列
'''可变序列，列表，字典'''
lst=[10,20,30]
print(id(lst))
lst.append(300)
print(id(lst))#改变值后，id不变
'''不可变序列，字符串，元组'''
s='hello'
print(id(s))
s+='world'
print(s,id(s))#改变值后，id改变

#元组的创建方式
#第一种使用小括号
t=('pyhon','hello','world')
print(t)
t='pyhon','hello','world',98#省略小括号
print(t)
t=(10,)#当元素只有一个时，要这样写，t才能是元组类型，逗号不能省略
print(t)
print(type(t))
#第二种创建方式使用内置函数tuple
a=tuple(('pyhon','hello','world','yyds'))
print(a)
print(type(a))
#空列表的创建方式
lst1=[]
lst2=list()
#空字典创建方式
d1={}
d2=dict()
#空元组
t1=()
t2=tuple()
print("空列表",lst1,lst2)
print("空字典",d1,d2)
print("空元组",t1,t2)

t=(10,[10,20],30)
print(t)
print(type(t))
print(t[0],type(t[0]),id(t[0]))
print(t[1],type(t[1]),id(t[1]))
print(t[2],type(t[2]),id(t[2]))
'''尝试将t[1]修改为100'''
#print(id(100))
#t[1]=100#元组不允许修改元素，
'''由于20和30组成是的列表，列表是可变的，所以可以在列表中添加元素'''
t[1].append(100)
print(t,id(t[1]))

#元组的遍历,元组是可迭代对象，可以使用forin遍历
t=("one","two",3,4)
print(t[0])#一个一个输，但要知道边界
for item in t:
    print(item)